version: '3'

services:
  application_layer:
    container_name: application_layer
    build: application_layer/
    command: bash -c 'while !</dev/tcp/project_db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --reload'
    depends_on:
      - project_db
    networks:
      - backend-network
      - frontend-network
  project_db:
    build: ./project_db
    container_name: project_db
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=project_db
    volumes:
      - project_db_data:/var/lib/postgresql/data/
    networks:
      - backend-network
  ui_layer:
    container_name: ui_layer
    build: ui_layer/
    command: streamlit run app/main.py --server.address="0.0.0.0" --server.port="80"  --server.headless=true
    networks:
      - backend-network
      - frontend-network
    ports: 
      - 80:80
volumes:
  project_db_data:

networks:
  backend-network:
    driver: bridge
    external: false
  frontend-network:
    external: true