version: '3'

services:
  ml_layer:
    build: ml_layer/
    command: bash -c 'while !</dev/tcp/datalake_db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --reload'
    volumes:
      - ./ml_jobs/app/ml_jobs.py:/app/ml_jobs.py
    ports: 
      - 8000:8000
  application_layer:
    build: application_layer/
    command: bash -c 'while !</dev/tcp/project_db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --reload'
    ports: 
      - 8001:8000
  data_layer:
    build: data_layer/
    command: bash -c 'while !</dev/tcp/datalake_db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --reload'
    ports: 
      - 8002:8000
  utility_layer:
    build: utility_layer/
    command: bash -c 'while !</dev/tcp/datalake_db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --reload'
    ports: 
      - 8003:8000
  reporting_layer:
    build: reporting_layer/
    command: bash -c 'while !</dev/tcp/datalake_db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --reload'
    ports: 
      - 8004:8000
  ui_layer:
    build: ui_layer/
    command: bash -c 'streamlit run app/main.py'
    depends_on:
      - ml_layer
    ports: 
      - 8501:8501
  project_db:
    build: ./project_db
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=project_db
    volumes:
      - project_db_data:/var/lib/postgresql/data/
  datalake_db:
    build: ./datalake_db
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=datalake_db
    volumes:
      - datalake_db_data:/var/lib/postgresql/data/
  redis:
    build: ./redis
    ports:
      - 6379:6379
  redis_r:
    build: ./redis
    ports:
      - 6380:6379
  ml_jobs:
    build: ./ml_jobs
    command: celery -A ml_jobs.app worker --loglevel=info
    volumes:
      - ./ml_jobs/app/:/app
    depends_on:
      - ml_layer
      - redis
    healthcheck:
        test: celery inspect ping -b redis://redis:6379/0 -d celery@ml_jobs
        interval: 30s
        timeout: 10s
        retries: 3
  ml_jobs_r:
    build: ./ml_jobs_r
    volumes:
      - ./ml_jobs_r/src/data/test.csv:/home/data/test.csv:ro
      - ./ml_jobs_r/src/master.R:/home/script/master.R
    depends_on:
      - ml_layer
      - redis_r
    healthcheck:
      test: celery inspect ping -b redis://redis:6379/0 -d celery@ml_jobs
      interval: 30s
      timeout: 10s
      retries: 3
  flower:
    build: ./flower
    command: celery -A ml_jobs.app flower --port=5555 --broker=redis://redis:6379/0
    volumes:
      - ./ml_jobs/app/:/app
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - ml_layer
      - redis
      - ml_jobs
volumes:
  project_db_data:
  datalake_db_data: